name: New User Request
description: Request Access to Arjuna
title: New User Request
labels:
  - "admin-tasks"

body:
  - type: input
    attributes:
      label: Andrew ID
      description: "Enter your AndrewID"
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Group Name
      description: "What group are you in?"
      options:
        - "Venkat Viswanathan"
        - "Noa Marom"
        - "Zachary Ulissi"
        - "Amir Barati Farimani"
        - "Other"
     validations:
      required: true
