name: New User Request
description: Request Access to Arjuna
title: New User Request
labels:
  - "admin-tasks"

body:
  - type: input
    attributes:
      label: Andrew ID
      description: "Enter your AndrewID"
    validations:
      required: true
